---
- name: Check SSH Connection
  ansible.builtin.include_role: 
    name: notmycloud.ssh_port
  vars:
    ssh:
      host: "{{ inventory_hostname }}"
      port: "{{ ansible_port }}"

# Fix issue with SSH not working on reboot
# https://askubuntu.com/questions/1109934/ssh-server-stops-working-after-reboot-caused-by-missing-var-run-sshd
  
# - name: Ensure /etc/tmpfiles.d exists
#   ansible.builtin.file:
#     path: /etc/tmpfiles.d
#     state: directory
#     mode: '0755'

# - name: Create sshd.conf for /run temp files
#   ansible.builtin.lineinfile:
#     path: /etc/tmpfiles.d/sshd.conf
#     create: yes
#     mode: '0644'
#     regexp: '^d /run/sshd'
#     line: d /run/sshd 0755 root root 

#https://www.reddit.com/r/debian/comments/sfzwco/ssh_server_crashing/
- name: Mitigation for SystemD SSH Socket race condition
  ansible.builtin.lineinfile:
    path: /lib/systemd/system/ssh@.service
    insertafter: '^#[Service]'
    regexp: '^RuntimeDirectoryPreserve='
    line: RuntimeDirectoryPreserve=yes
  failed_when: false

- name: Reload SystemD
  command: systemctl daemon-reload

- name: Harden SSH
  ansible.builtin.include_role:
    name: devsec.hardening.ssh_hardening
  vars:
    ssh_server_ports:
      - "{{ ansible_port }}"
    ssh_permit_root_login: without-password
    ssh_print_motd: true
    ssh_print_pam_motd: true
    ssh_print_debian_banner: true
    ssh_print_last_log: true
    sftp_enabled: true
    sftp_chroot: false
    ssh_client_port: 22
    ssh_client_compression: true
    ssh_compression: true
    ssh_max_auth_retries: 3
    ssh_max_sessions: 3
    ssh_custom_options:
      - 'GlobalKnownHostsFile /etc/ssh/known_hosts.d/%k /etc/ssh/known_hosts'
      - 'UserKnownHostsFile ~/.ssh/known_hosts.d/%k ~/.ssh/known_hosts'

- name: Scan SSH Host keys for well known sites
  ansible.builtin.include_role:
    name: notmycloud.ssh_keyscan
  vars:
    global_known_hosts: true
    ssh:
      port: "{{ keyscan.port }}"
      host: "{{ keyscan.host }}"
  loop: "{{ ssh_well_known_hosts }}"
  loop_control:
    loop_var: keyscan