---
- name: Create /etc/profile.d folder
  ansible.builtin.file:
    path: /etc/profile.d
    state: directory
    mode: '0755'

- name: Setup {{ default_shell | default(shell) }} Aliases
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
      - shell/{{ default_shell | default(shell) }}-aliases.yaml
      skip: True

- name: Setup {{ default_shell | default(shell) }} Functions
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
      - shell/{{ default_shell | default(shell) }}-functions.yaml
      skip: True

- name: Add Shell Aliases
  ansible.builtin.lineinfile:
    dest: "/etc/profile.d/00-ansible-{{ default_shell | default(shell) }}-shell-aliases.sh"
    create: true
    mode: 0644
    line: 'alias {{ alias.name }}="{{ alias.command }}"'
    regexp: "^alias {{ alias.name }}="
  loop: "{{ shell_aliases }}"
  loop_control:
    loop_var: alias

- name: Create Bash Function | apt-get
  ansible.builtin.blockinfile:
    path: "/etc/profile.d/01-ansible-{{ default_shell | default(shell) }}-function-apt-get.sh"
    create: true
    mode: 0644
    block: |
      apt-get () {
        if ! command -v apt-get &> /dev/null; then
          echo "apt-get not be found, are you on Debian?"
          return
        fi
        if [[ $(id -u) -ne 0 ]]; then
          command sudo apt-get "$@"
        else
          command apt-get "$@"
        fi
      }

- name: Create Bash Function | apt
  ansible.builtin.blockinfile:
    path: "/etc/profile.d/01-ansible-{{ default_shell | default(shell) }}-function-apt.sh"
    create: true
    mode: 0644
    block: |
      apt () {
        if ! command -v apt &> /dev/null; then
          echo "apt not be found, are you on Debian?"
          return
        fi
        if [[ $(id -u) -ne 0 ]]; then
          command sudo apt "$@"
        else
          command apt "$@"
        fi
      }