---
- name: Setup default {{ default_shell | default(shell) }} settings
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
      - shell/{{ default_shell | default(shell) }}.yaml
      skip: True

- name: Create Bash Function | apt-get
  blockinfile:
    path: "/etc/profile.d/01-ansible-function-apt-get.sh"
    create: yes
    mode: 0644
    block: |
      apt-get () {
        if ! command -v apt-get &> /dev/null; then
          echo "apt-get not be found, are you on Debian?"
          return
        fi
        if [[ $(id -u) -ne 0 ]]; then
          command sudo apt-get "$@"
        else
          command apt-get "$@"
        fi
      }

- name: Create Bash Function | apt
  blockinfile:
    path: "/etc/profile.d/01-ansible-function-apt.sh"
    create: yes
    mode: 0644
    block: |
      apt () {
        if ! command -v apt &> /dev/null; then
          echo "apt not be found, are you on Debian?"
          return
        fi
        if [[ $(id -u) -ne 0 ]]; then
          command sudo apt "$@"
        else
          command apt "$@"
        fi
      }
